{{- if .Values.openshiftMarketplace.istio.subscription.create -}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator.v1.1.2.2
---
{{- end -}}
{{- if .Values.openshiftMarketplace.istio.controlPlane.create -}}
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: full-install
  namespace: {{ .Values.openshiftMarketplace.istio.controlPlane.namespace }}
spec:

  istio:
    global:
      proxy:
        resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 128Mi

    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 2
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 2

    mixer:
      policy:
        autoscaleEnabled: false

    telemetry:
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 1G
        limits:
          cpu: 500m
          memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100

    kiali:
      enabled: false

    grafana:
      enabled: false

    tracing:
      enabled: false
    jaeger:
      template: all-in-one
---
{{- end -}}
{{- if .Values.openshiftMarketplace.istio.memberRoll.create -}}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ .Values.openshiftMarketplace.istio.memberRoll.namespace }}
  finalizers:
    - maistra.io/istio-operator
spec:
  members:
{{ toYaml .Values.openshiftMarketplace.istio.memberRoll.members | indent 4 }}
{{- end -}}