{{- if .Values.openshiftMarketplace.seldonCore.istioGateway.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.openshiftMarketplace.seldonCore.istioGateway.name }}
  namespace: {{ .Values.openshiftMarketplace.seldonCore.istioGateway.namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
{{- end -}}