apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        #registry.connect.redhat.com/seldonio/seldon-deploy-operator:1.0.0
      - image: quay.io/seldon/seldon-deploy-server-operator:1.0.0
        imagePullPolicy: Always
        args:
        - "--enable-leader-election"
        - "--leader-election-id=seldon-deploy-operator"
        name: manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "seldon-deploy-operator"
          #registry.connect.redhat.com/seldonio/seldon-deploy:0.7
          - name: RELATED_IMAGE_DEPLOYMENT
            value: seldonio/seldon-deploy-server-ubi:1.2.0
          #registry.connect.redhat.com/seldonio/seldon-loadtester:0.1
          - name: RELATED_IMAGE_LOADTEST
            value: seldonio/hey-loadtester-ubi:0.1
          #registry.connect.redhat.com/seldonio/alibi-detect-server:1.2.1
          - name: RELATED_IMAGE_ALIBIDETECT
            value: seldonio/alibi-detect-server:1.6.0-PR2923
          #registry.connect.redhat.com/seldonio/seldon-request-logger:1.2.1
          - name: RELATED_IMAGE_REQUESTLOGGER
            value: seldonio/seldon-request-logger:1.7.0
          #registry.connect.redhat.com/seldonio/kubectl:1.14.3
          - name: RELATED_IMAGE_KUBECTL
            value: seldonio/kubectl:1.14.3
          #registry.connect.redhat.com/seldonio/seldon-core-s2i-python37:1.5.0 - doesn't exist yet
          - name: RELATED_IMAGE_BATCH_PROCESSOR
            value: seldonio/seldon-core-s2i-python37:1.5.1
          #not a seldon image - would need to create ubi version (but is argo or minio available certified?)
          - name: RELATED_IMAGE_MINIO_CLIENT
            value: seldonio/mc-ubi:1.0
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
