apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for machinelearning.seldon.io/v1alpha1, Kind: SeldonDeploy
##
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeploys
  - seldondeploys/status
  - seldondeploys/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "replicasets"
- verbs:
  - "*"
  apiGroups:
  - "eventing.knative.dev"
  resources:
  - "triggers"
- verbs:
  - "*"
  apiGroups:
  - "networking.istio.io"
  resources:
  - "virtualservices"
  - "gateways"
- verbs:
    - "*"
  apiGroups:
    - "machinelearning.seldon.io"
  resources:
    - "*"
- verbs:
    - "*"
  apiGroups:
    - "operators.coreos.com"
  resources:
    - "subscriptions"
- verbs:
    - "*"
  apiGroups:
    - "eventing.knative.dev"
  resources:
    - "triggers"
- verbs:
    - "*"
  apiGroups:
    - "batch"
  resources:
    - "jobs"
- verbs:
    - "*"
  apiGroups:
    - "monitoring.coreos.com"
  resources:
    - "servicemonitors"
    - "podmonitors"
# +kubebuilder:scaffold:rules
