# permissions for end users to edit seldondeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seldondeploy-editor-role
rules:
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeploys/status
  verbs:
  - get
