apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: delete-hook-role
  namespace: openshift-operators
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
    verbs:
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon-deploy-rolebinding
  namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-hook-role
subjects:
  - kind: ServiceAccount
    name: delete-hook
    namespace: openshift-operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-hook
  namespace: openshift-operators
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-job
  namespace: openshift-operators
spec:
  template:
    metadata:
      name: delete-job
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "bitnami/kubectl:1.16.3"
          command: ["kubectl","delete","clusterserviceversion","-n","openshift-operators","seldon-operator.v1.1.0"]
      serviceAccount: delete-hook
      serviceAccountName: delete-hook