apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: seldon-prometheus
  labels:
    prometheus: k8s
  namespace: seldon
spec:
  replicas: 2
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
  alerting:
    alertmanagers:
      - namespace: openshift-monitoring
        name: alertmanager-main
        port: web
