apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-deploy-operator-subscription
  namespace: marketplace
spec:
  channel: alpha
  name: seldon-deploy-operator
  source: seldon-operators
  sourceNamespace: marketplace
