apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-deploy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seldon-deploy-operator
  template:
    metadata:
      labels:
        name: seldon-deploy-operator
    spec:
      serviceAccountName: seldon-deploy-operator
      containers:
        - name: seldon-deploy-operator
          image: seldonio/seldon-deploy-operator:0.7.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "seldon-deploy-operator"
