apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "machinelearning.seldon.io/v1alpha1",
          "kind": "SeldonDeploy",
          "metadata": {
            "name": "example-seldondeploy",
            "namespace": "seldon"
          },
          "spec": {
            "affinity": {},
            "argocd": {
              "url": "https://argocd-server.argocd.svc.cluster.local"
            },
            "docker": {
              "user": "unkown"
            },
            "elasticsearch": {
              "jwtSecretKey": "jwt-elastic.txt",
              "jwtSecretName": "jwt-elastic",
              "url": "https://elasticsearch.openshift-logging:9200"
            },
            "enableAppAnalytics": true,
            "enableAppAuth": false,
            "env": {
              "GITOPS_FORMAT": "json",
              "USERID_CLAIM_KEY": "name"
            },
            "external": {
              "host": "",
              "protocol": "http"
            },
            "fullnameOverride": "",
            "github": {
              "email": "",
              "token": "",
              "user": ""
            },
            "image": {
              "pullPolicy": "Always",
              "repository": "ryandawsonuk/seldon-deploy",
              "tag": "0.7.0-dev"
            },
            "imagePullSecrets": [
              {
                "name": "regcred"
              }
            ],
            "ingress": {
              "annotations": {},
              "enabled": false,
              "hosts": [
                {
                  "host": "chart-example.local",
                  "paths": []
                }
              ],
              "tls": []
            },
            "kfserving": {
              "curlForm": "MODEL_NAME={{ .ModelName }}\u003cbr\u003e\nCLUSTER_IP=$(kubectl -n {{ .IngressNamespace }} get service {{ .IngressServiceName }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')\u003cbr\u003e\nSERVICE_HOSTNAME=$(kubectl get inferenceservice {{ .ModelName }} -o jsonpath='{.status.url}' | cut -d \"/\" -f 3)\u003cbr\u003e\ncurl -v -H \"Host: ${SERVICE_HOSTNAME}\" http://$CLUSTER_IP/v1/models/$MODEL_NAME:predict -d '{{ .Payload }}'\n",
              "enabled": false,
              "explainForm": "http://{{ .IngressServiceName }}/v1/models/{{ .ModelName }}:explain",
              "protocol": "http",
              "requestForm": "http://{{ .IngressServiceName }}/v1/models/{{ .ModelName }}:predict"
            },
            "loadtest": {
              "image": {
                "repository": "seldonio/hey-loadtester",
                "tag": 0.1
              }
            },
            "nameOverride": "",
            "nodeSelector": {},
            "openshiftMarketplace": {
              "istio": true,
              "seldonCore": {
                "istioGateway": true,
                "subscription": true
              }
            },
            "prometheus": {
              "knative": {
                "url": "https://prometheus-k8s.openshift-monitoring:9091/api/v1/"
              },
              "seldon": {
                "jwtSecretKey": "jwt-elastic.txt",
                "jwtSecretName": "jwt-elastic",
                "namespaceMetricName": "namespace",
                "resourceMetricsUrl": "https://prometheus-k8s.openshift-monitoring:9091/api/v1/",
                "serviceMetricName": "exported_service",
                "url": "http://prometheus-operated.seldon:9090/api/v1/"
              }
            },
            "rbac": {
              "clusterWide": false,
              "create": true
            },
            "replicaCount": 1,
            "resources": {},
            "seldon": {
              "curlForm": "CLUSTER_IP=$(kubectl -n {{ .IngressNamespace }} get service {{ .IngressServiceName }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')\u003cbr\u003e\ncurl -k -H \"X-Auth-Token: {{ .Token }} \" -H \"Content-Type: application/json\" http://$CLUSTER_IP/seldon/{{ .Namespace }}/{{ .ModelName }}/api/v0.1/predictions -d '{{ .Payload }}'\n",
              "enabled": true,
              "explainForm": "http://{{ .ModelName }}-{{ .Predictor }}-explainer.{{ .Namespace }}:9000/v1/models/{{ .ModelName }}:explain",
              "seldonRequestForm": "http://{{ .IngressServiceName }}/seldon/{{ .Namespace }}/{{ .ModelName }}/api/v0.1/predictions",
              "tensorFlowCurlForm": "CLUSTER_IP=$(kubectl -n {{ .IngressNamespace }} get service {{ .IngressServiceName }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')\u003cbr\u003e\ncurl -k -H \"X-Auth-Token: {{ .Token }} \" -H \"Content-Type: application/json\" http://$CLUSTER_IP/seldon/{{ .Namespace }}/{{ .ModelName }}/v1/models/:predict -d '{{ .Payload }}'\n",
              "tensorflowRequestForm": "http://{{ .IngressServiceName }}/seldon/{{ .Namespace }}/{{ .ModelName }}/v1/models/:predict"
            },
            "service": {
              "port": 80,
              "type": "ClusterIP"
            },
            "serviceAccount": {
              "create": true
            },
            "serviceAccountName": "seldon-deploy",
            "skipVerifyGit": true,
            "skipVerifyHttpCalls": true,
            "tolerations": [],
            "virtualService": {
              "create": true,
              "gateways": [
                "seldon-gateway.istio-system.svc.cluster.local"
              ],
              "istioIngressService": "istio-ingressgateway",
              "istioNamespace": "istio-system",
              "kfServingIngressService": "kfserving-ingressgateway",
              "prefix": "/seldon-deploy/"
            }
          }
        }
      ]
    capabilities: Basic Install
  name: seldon-deploy-operator.v0.6.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: A seldon deployapplication
        displayName: Seldon Delpoyment
        kind: SeldonDeploy
        name: seldondeploys.machinelearning.seldon.io
        resources:
          - kind: SeldonDeploy
            name: seldondeploys.machinelearning.seldon.io
            version: v1alpha1
          - kind: Deployment
            name: ""
            version: v1
          - kind: ConfigMap
            name: ""
            version: v1
          - kind: Service
            name: ""
            version: v1
          - kind: ReplicaSet
            name: ""
            version: v1
          - kind: Pod
            name: ""
            version: v1
          - kind: Secret
            name: ""
            version: v1
          - kind: ClusterRole
            name: ""
            version: v1
          - kind: Role
            name: ""
            version: v1
          - kind: RoleBinding
            name: ""
            version: v1
          - kind: ServiceAccount
            name: ""
            version: v1
          - kind: ClusterRoleBinding
            name: ""
            version: v1
        specDescriptors:
          - description: kfserving active
            displayName: kfserving
            path: kfserving
          - description: resources
            displayName: resources
            path: rsources
          - description: virtualService
            displayName: virtualService
            path: virtualService
          - description: Environment vars to add
            displayName: env
            path: env
          - description: imagePullSecrets
            displayName: imagePullSecrets
            path: imagePullSecrets
          - description: nameOverride
            displayName: nameOverride
            path: nameOverride
          - description: prometheus
            displayName: prometheus
            path: prometheus
          - description: skipVerifyHttpCalls
            displayName: skipVerifyHttpCalls
            path: skipVerifyHttpCalls
          - description: enableAppAuth
            displayName: enableAppAuth
            path: enableAppAuth
          - description: external
            displayName: external
            path: external
          - description: loadtest
            displayName: loadtest
            path: loadtest
          - description: ingress
            displayName: ingress
            path: ingress
          - description: lite
            displayName: lite
            path: lite
          - description: tolerations
            displayName: tolerations
            path: tolerations
          - description: serviceAccountName
            displayName: serviceAccountName
            path: serviceAccountName
          - description: argocd
            displayName: argocd
            path: argocd
          - description: elasticsearch
            displayName: elasticsearch
            path: elasticsearch
          - description: fullnameOverride
            displayName: fullnameOverride
            path: fullnameOverride
          - description: resources
            displayName: resources
            path: resources
          - description: seldon
            displayName: seldon
            path: seldon
          - description: replicaCount
            displayName: replicaCount
            path: replicaCount
          - description: skipVerifyGit
            displayName: skipVerifyGit
            path: skipVerifyGit
          - description: affinity
            displayName: affinity
            path: affinity
          - description: enableAppAnalytics
            displayName: enableAppAnalytics
            path: enableAppAnalytics
          - description: github
            displayName: github
            path: github
          - description: image
            displayName: image
            path: image
          - description: nodeSelector
            displayName: nodeSelector
            path: nodeSelector
          - description: rbac
            displayName: rbac
            path: rbac
          - description: service
            displayName: service
            path: service
          - description: serviceAccount
            displayName: serviceAccount
            path: serviceAccount
          - description: docker
            displayName: docker
            path: docker
          - description: openshiftMarketplace
            displayName: openshiftMarketplace
            path: openshiftMarketplace
        statusDescriptors:
          - description: conditions
            displayName: conditions
            path: conditions
          - description: deploy version released
            displayName: deployedRelease
            path: deployedRelease
        version: v1alpha1
    required:
      - kind: SeldonDeployment
        name: seldondeployments.machinelearning.seldon.io
        version: v1
        displayName: seldon core dep
        description: seldon core dependency
      - kind: ServiceMeshControlPlane
        name: maistra.io
        version: v1
        displayName: istio control plane
        description: istio control plane
      - kind: ServiceMeshMemberRoll
        name: maistra.io
        version: v1
        displayName: istio member roll
        description: istio member roll
  displayName: Seldon Deploy Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - seldon-deploy-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - machinelearning.seldon.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.istio.io
          resources:
          - virtualservices
          verbs:
          - '*'
        serviceAccountName: seldon-deploy-operator
      deployments:
      - name: seldon-deploy-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: seldon-deploy-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: seldon-deploy-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: seldon-deploy-operator
                image: seldonio/seldon-deploy-operator:0.6.0
                imagePullPolicy: IfNotPresent
                name: seldon-deploy-operator
                resources: {}
              serviceAccountName: seldon-deploy-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.6.3
