apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: seldon-request-logger-trigger
  namespace: seldon-logs
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: seldon-request-logger
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: seldon-request-logger
  namespace: seldon-logs
spec:
  template:
    metadata:
      labels:
        fluentd: "true"
        maistra.io/expose-route: "true"
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: docker.io/seldonio/seldon-request-logger:0.3.1
          imagePullPolicy: Always
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch.openshift-logging"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_PROTOCOL
              value: "https"
            - name: ELASTICSEARCH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-elastic
                  key: jwt-elastic.txt
          resources:
            limits:
              cpu: "0.8"
              memory: 200M
            requests:
              cpu: 200m
              memory: 100M